// Mock contract IDs for development/demo
export const DEMO_CONTRACT_IDS = { 
  LOANS: "CCXQXRJFG5LIETP6TTKCCLD6K44CNJPUMNS4MZAN2Y2QJ2LQDZ3TDXDW",
  LIQUIDATION: "CCWO5QNDHHQMLD4QR2WPZKCPIXMPX4PSADHYCMZGM7UEDQKZHQBULVVP",
  POLICY: "CCEYTWH34EZLL5GGEAMQATUPGW6LSEZI3WPC2TKLPEPQVCZISHZ36HNH",
  ORACLE: "CCUDGCPV7OSYF5XKNFRHAVTGV5A2QEGJRLBGFMHOGZODW63CBQR77AQW",
  KYC: "CCUDGCPV7OSYF5XKNFRHAVTGV5A2QEGJRLBGFMHOGZODW63CBQR77AQW"
}